# Spring Boot configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgis:5432/udemy-curso
    username: dpgis
    password: pgdpgis@urbes123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
security:
  jwt:
    token:
      secret-key: 12345678901234567890123456789012
      expiration-in-seconds: 3600

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true
